### PR TITLE
Oc 439

### PR DESCRIPTION
**Pull request by matthewberryman**
@ZaraGlynn can you please help me by reviewing this asap against the ticket description?
Noting that the smoothness of search bar to being sticky still needs some work.

### CODE REVIEW

**Comment by matthewberryman** [comment]
@herbertzhai 
The home icon is wrong - it should be src/images/logo/OA_symbol.svg per note at top of ticket. However, we may get another logo soon, but in the mean time it would be good to still get that one in so we can test with an svg file as the new logo would be svg.

The search stickyness on scroll issue would be good to fix but I don't think it's a showstopper.

There is an issue where the text can run into the home icon just before it swaps to the hamburger menu bar for the menu:
Screen Shot 2020-05-20 at 3 39 25 pm

In future please open the PR yourself, that way I can be assigned as a reviewer in github which unlocks the review functionalities properly.

**Comment by herbertzhai** [comment]
Got it, I will make PR from my github in the future. I will fix the home icon and text run into the icon problems now. Regards, Herbert -------- Original message --------From: Matthew Berryman <notifications@github.com>Date: Wed, 20 May 2020, 15:47To: AcrossTheCloud/TBA21-client <TBA21-client@noreply.github.com>Cc: Herbert Zhai <herbertchak@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [AcrossTheCloud/TBA21-client] Oc 439 (#249)
@herbertzhai
The home icon is wrong - it should be src/images/logo/OA_symbol.svg per note at top of ticket. However, we may get another logo soon, but in the mean time it would be good to still get that one in so we can test with an svg file as the new logo would be svg.
The search stickyness on scroll issue would be good to fix but I don't think it's a showstopper.
There is an issue where the text can run into the home icon just before it swaps to the hamburger menu bar for the menu:

In future please open the PR yourself, that way I can be assigned as a reviewer in github which unlocks the review functionalities properly.

**Comment by ZaraGlynn** [comment]
image
Slight touching between the icon and the menu here

**Comment by matthewberryman** [comment]
@ZaraGlynn I am just following up on this now and noticed @herbertzhai has done the work in another branch in another repository and opened a new PR against this repo. 

Bert there is no need to have a separate repo, as feature branches in this repo to which you have access are fine. Can you please merge your changes into this branch of this repo and let us know when good to review by commenting on this.

**Comment by matthewberryman** [comment]
@herbertzhai @ZaraGlynn I had a few minutes spare so I merged Bert's separate branch in other repo into this one with this commit:
https://github.com/AcrossTheCloud/TBA21-client/pull/249/commits/2b7e006895d75117f83e964cc6c7f723b1d61266
I think I resolved the merge conflicts ok (just extra spacing issues) but Bert please check and Zara if you could now re-test after pulling this branch

**Comment by matthewberryman** [comment]
circleci picked up some issues otherwise generated by the merge, resolved in 
https://github.com/AcrossTheCloud/TBA21-client/pull/249/commits/2b7e006895d75117f83e964cc6c7f723b1d61266
@ZaraGlynn note to pull this down too - sorry about that I should have tested locally first

**Comment by matthewberryman** [comment]
I'm going to merge this once circleci has also tested, as it's looking good my end and I would like to get the client to review too, but @ZaraGlynn if you could still pull this branch and take a look and test that would be great.

**Comment by herbertzhai** [comment]
Sorry, Matthew. I do not know how the issue happened. Maybe I failed to
update the local codes before I start changing. Have you finished the merge
or I should push again under newest version?

Matthew Berryman <notifications@github.com> 于2020年5月21日周四 下午3:53写道：

**Comment by matthewberryman** [comment]
The issue happened because you are working from a forked repo. There’s no need to do that as you have access here. Please review the commits I have linked and also retest your end.

Regards,
Matthew
sent from my iPhone
________________________________

**Comment by herbertzhai** [comment]
Ok. I will pull it and retest now. Regards, Herbert -------- Original message --------From: Matthew Berryman <notifications@github.com>Date: Thu, 21 May 2020, 16:11To: AcrossTheCloud/TBA21-client <TBA21-client@noreply.github.com>Cc: Herbert Zhai <herbertchak@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [AcrossTheCloud/TBA21-client] Oc 439 (#249)

The issue happened because you are working from a forked repo. There’s no need to do that as you have access here. Please review the commits I have linked and also retest your end.







Regards,



Matthew



sent from my iPhone



________________________________

**Comment by herbertzhai** [comment]
I pulled the code. It is all right. However, I found a bug: there is a small strip on the top of the first video page. This is because I use a div wrapped the search bar to make it smooth when scrolling. I will fix it soon. There is a big thunderstorm in Bowral now and make my home internet interrupt. I will continue work after all as normal. Regards, Herbert -------- Original message --------From: Matthew Berryman <notifications@github.com>Date: Thu, 21 May 2020, 16:11To: AcrossTheCloud/TBA21-client <TBA21-client@noreply.github.com>Cc: Herbert Zhai <herbertchak@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [AcrossTheCloud/TBA21-client] Oc 439 (#249)

The issue happened because you are working from a forked repo. There’s no need to do that as you have access here. Please review the commits I have linked and also retest your end.







Regards,



Matthew



sent from my iPhone



________________________________

**Pull request merged**
