### PR TITLE
Oc 383

### PR DESCRIPTION
**Pull request by Dan-Wood**

### CODE REVIEW

**Comment by Dan-Wood** [comment]
3 will only happen if the video is larger than then content loading.

I'd hope the video is < 5MB.

**Comment by matthewberryman** [comment]
`curl -I https://video-streaming.ocean-archive.org/loading_video.mp4`:
HTTP/2 200 
content-type: video/mp4
content-length: 79140043

I don't think I can get it much smaller without it looking dodgy but I will try. It seems fine anyhow re timing.

**Comment by matthewberryman** [comment]
I've gone with 720p and tweaked some other settings and it doesn't look too bad and clocks in at 53,697,335 bytes. I don't think I can get it smaller short of trimming the video in such a way that a loop looks really smooth.

**Comment by Dan-Wood** [comment]
Boxing shouldn't happen, it's 100% height and width with object-fit cover.

Although on the rare occasion your browser is processing it, that may be the problem.

**Pull request merged**
