### PR TITLE
Dev redux

### PR DESCRIPTION
**Pull request by Dan-Wood**
Redux implementation, with folder structure for actions/reducers/rootReducer and the Actual store using React-Redux, Redux and Redux-Thunk (middleware for async actions).

Along with ViewItem and ViewItems redux storage.

### CODE REVIEW

**Comment by matthewberryman** [comment]
Hold on, I am getting an error

**Comment by mehrdadgit** [comment]
No @matthewberryman just reviewed the code visually, sorry; I am getting the same error, seems like a TS error ? Is redux and redux-thunk compatible with TS @Dan-Wood ?

**Comment by matthewberryman** [comment]
> No @matthewberryman just reviewed the code visually, sorry; I am getting the same error, seems like a TS error ? Is redux and redux-thunk compatible with TS @Dan-Wood ?

It's not a TS error; from the error message it's because something isn't being passed in properly so it's undefined and then apply isn't working. Perhaps it's because I'm not logged in but data is being fetched as if I am (most of the API calls require login)—maybe need to add a check? I haven't yet started reading through the code.

**Comment by matthewberryman** [comment]
Just eyeballing it now in conjunction with the IAM policy, it's only working with get items, so it should be fine (that can be accessed via dev unauth policy). Problem lies elsewhere methinks.

**Pull request merged**
