### PR TITLE
Config and deploy updates

### PR DESCRIPTION
**Pull request by mehrdadgit**

### CODE REVIEW

**Review by matthewberryman — CHANGES_REQUESTED** [review]
1. .env file should not be checked in, to prevent accidental committing of any sensitive information a developer might add there. Please keep the `DISABLE_NEW_JSX_TRANSFORM=true` in package.json, and also there should be a .gitignore entry for .env too.
2. Instructions in README.md will need updating for the revised `REACT_APP_DEPLOY_ENV` env var.

Rest looks good, thanks.

**Comment by mehrdadgit** [comment]
> 1. .env file should not be checked in, to prevent accidental committing of any sensitive information a developer might add there. Please keep the `DISABLE_NEW_JSX_TRANSFORM=true` in package.json, and also there should be a .gitignore entry for .env too.
> 2. Instructions in README.md will need updating for the revised `REACT_APP_DEPLOY_ENV` env var.
> 
> Rest looks good, thanks.

Thanks! 
1. Added `.gitignore` entry for `.env`; and pushed a `.env.example` for setting `DISABLE_NEW_JSX_TRANSFORM=true` . I am kinda against adding it to `package.json` for simplicity and to avoid having multiple `npm start` scripts for each local dev OS (windows/Mac/Linux). Also noting `DISABLE_NEW_JSX_TRANSFORM` is temporary anyway and can go after upgrading to React 17.
2. Done, and updated for both  `DISABLE_NEW_JSX_TRANSFORM` and `REACT_APP_DEPLOY_ENV`.

Cheers

**Review by matthewberryman — CHANGES_REQUESTED** [review]
I'm a bit reluctant to move the JSX out to a sample .env that must be copied over, because it's extra work that a developer must do to get started / update. It's also something that I would need to put into build envs x3 (CircleCI and manually in CodePipeline), and then remove manually as an extra step when we get to React 17.  Plus it's not for now an optional thing either. So please leave it in package.json and also update the README.md accordingly.

**Comment by mehrdadgit** [comment]
> I'm a bit reluctant to move the JSX out to a sample .env that must be copied over, because it's extra work that a developer must do to get started / update. It's also something that I would need to put into build envs x3 (CircleCI and manually in CodePipeline), and then remove manually as an extra step when we get to React 17. Plus it's not for now an optional thing either. So please leave it in package.json and also update the README.md accordingly.

I have already added to all buildspecs; so there shouldnot be any problem there, and good to do... That way, I basically cannot do `npm start` on windows and that has already caused me some time and confustion when I switch between projects... I suggest please let us keep it that way and I can easily remove them all once upgraded to react 17. Or when I switch back to Mac.

**Review by matthewberryman — APPROVED** [review]

**Comment by matthewberryman** [comment]
> I had already added them to both buildspecs and circleci `config.yml`; so there should not be any problem there, and good to go ... Plus I don't think any manual update of the piplines will be required?... That way, I basically cannot do `npm start` on windows and that has already caused me some time and confustion when I switch between projects... I suggest please let us keep it that way and I can easily remove them all once upgraded to react 17. Or when I switch back to Mac.

I am pretty sure that staging CodePipeline will need a tweak to point to the staging-specific buildspec, will action that now and merge. I take your point about Windows and env vars so this seems like the best thing all-things considered as I do want to support Windows dev. Can you please Slack me re React 17 when you have a moment.

**Comment by matthewberryman** [comment]
Oh wait, I already had a staging-specific buildspec, my bad. All good to merge, thanks @mehrdadgit

**Pull request merged**
